[profile.default]
src = "src"
out = "out"
libs = ["lib"]
build_info = true
extra_output = ["storageLayout"]
ast = true

[rpc_endpoints]
sepolia = "https://sepolia.drpc.org"
base_sepolia = "wss://base-sepolia-rpc.publicnode.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
